
import { Inter } from "next/font/google";
import "./globals.css";
// import Navbar from "./component/Navbar/page";
// import Footer from "./component/Navbar/Footer/Footer";
// import BottomNav from "./component/Navbar//Side/BotmNav/BotmNav";
// import AuthProvider from "./services/AuthProvider";
// import Navbar from "@/component/Navbar/page";
// import Footer from "@/component/Navbar/Footer/Footer";
// import BottomNav from "@/component/Navbar/Side/BotmNav/BotmNav";
// import AuthProvider from "@/services/AuthProvider";
import Navbar from "./component/Navbar/page";
import AuthProvider from "@/services/AuthProvider";
import Footer from "./component/Navbar/Footer/Footer";
import BottomNav from "./component/Navbar/Side/BotmNav/BotmNav";
import { Nunito } from 'next/font/google';



const nunito = Nunito({
  weight: ['400', '600', '700'], // Choose weights you need
  subsets: ['latin'],            // Include subsets (e.g., 'latin')
});

export const metadata = {
  title: "BioCare",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="">
      
      <body className={nunito.className}>
      <AuthProvider>
        <Navbar />
        {children}
      
        <Footer />
          <BottomNav />
          </AuthProvider>
      </body>
     
     
    </html>
  );
}
